name: Battle Bot Builder

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

jobs:
  KiCad_Hardware:
    runs-on: ubuntu-latest
    name: KiCad Hardware

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          # Config file
          config: Hardware/config.kibot.yaml
          # Prefix for output in config file.
          dir: _hardwareOutput

          # Hardware Files
          schema: "Hardware/BattleBot_Motherboard/BattleBot_Motherboard.kicad_sch"
          board: "Hardware/BattleBot_Motherboard/BattleBot_Motherboard.kicad_pcb"

      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: BattleBot-Hardware
          path: _hardwareOutput

  make_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    needs: [KiCad_Hardware]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: sudo apt update

      - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk inkscape imagemagick

      - name: Install requirements
        run: pip install -r Docs/requirements.txt

      # Download artifacts from other builds
      - uses: actions/download-artifact@v2
        with:
          name: BattleBot-Hardware
          path: _hardwareOutput

      - run: cd Docs && make latexpdf

      - run: mv Docs/_build/latex/*.pdf Docs/_build/latex/BattleBot-Manual.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: BattleBot-Manual
          path: Docs/_build/latex/BattleBot-Manual.pdf

  make_firmware:
    runs-on: ubuntu-latest
    name: Firmware Builder

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Run PlatformIO
        run: cd Firmware && make

      - uses: actions/upload-artifact@v2
        with:
          name: BattleBot-Firmware
          path: Firmware/.pio/build/megaatmega2560/firmware.*

  delint:
    runs-on: ubuntu-latest
    name: Delinter

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Run Delinter
        run: cd Firmware && pio check

  publish:
    # Only run on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Publish
    needs: [make_docs, KiCad_Hardware, make_firmware]

    steps:
      # Download artifacts
      - uses: actions/download-artifact@v2
        with:
          name: BattleBot-Manual

      - uses: actions/download-artifact@v2
        with:
          name: BattleBot-Hardware

      - uses: actions/download-artifact@v2
        with:
          name: BattleBot-Firmware

      - run: mkdir -p _staging/

      - run: cp *.pdf _staging/

      - run: cp *.step _staging/

      - run: cp *.hex _staging/ && cp *.elf _staging/

      - name: Upload Docs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "_staging/*"
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          body: "SNHU Robotics, Automated with github ci/cd."
          file_glob: true
